name: DVWA SAST & DAST Scan

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  sast:
    name: Run SAST (Semgrep with custom rules)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep with Custom SQL Injection Rules
        run: |
          semgrep --config p/owasp-top-ten --include "**/*.php" --sarif --output semgrep-results.sarif

      - name: Upload SAST results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif

 
